version: '3.3'
name: booking2

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ${CONTAINER_NAME:-mssql}
    hostname: ${HOSTNAME:-mssql}
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${PASSWORD:-zaq1@WSX}
    ports:
      - ${PORT:-1433}:1433
    volumes:
      - ../db:/db
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr &
        sleep 10
        sh /db/init.sh
        sleep infinity
